---
name: Push Workflow
on:
  push:
    branches:
      - main
jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create log file
        run: |
          echo "Workflow executed at $(date)" > log.txt

      - name: Print working directory
        run: |
          pwd

      - name: Display log contents
        run: |
          cat log.txt

      - name: Custom message
        run: |
          echo "Guy Sharp - AICO cohort - one green check at a time"
